### ISSUE TITLE
headers don't match up

### ISSUE THREAD

**Issue by lexnederbragt** [richardmleggett/nextclip#12]
Hi,

Nextclip is throwing this error:

Error: headers don't match up: @M00903:39:000000000-A2197:1:1101:2114:16514/1 and @M00903:39:000000000-A2197:1:1101:2114:16514/2

The read IDs have the string '@M00903:39:000000000-A2197:1:1101:2114:16514' in common. Why is it then still throwing the error? Is it expecting a different format? The reads are from baseSpace: https://basespace.illumina.com/projects/294296/Nextera-Mate-Pair-E-Coli (downloaded over a year ago)

**Comment by ZhuYan-SIPPE** [comment]
Hi, Richard,

Nextclip reports these errors:
Warning: read shorter than minimum read size (64) - ignoring
Warning: Only managed to get one read - pair ignored
Error: headers don't match up: ......

My script was:  nextclip -i 0.data/cleandata/IS2k_1_1.clean.fq.gz -j 0.data/cleandata/IS2k_1_2.clean.fq.gz -o 0.data/dealdata/IS2k_1_nextclip -l nextclip.log -m 50 -n 189748769

I can ensure that all reads are 150bp length, and pair-end.
My reads' head are like this: 
@A00192:209:HHH3JDSXX:2:1101:2239:1016 1:N:0:ACCTCCAA+TCTTTCCC
@A00192:209:HHH3JDSXX:2:1101:2239:1016 2:N:0:ACCTCCAA+TCTTTCCC

My nextclip is v1.3.2, and I ran the example files successfully.

**Comment by richardmleggett** [comment]
Hi,
The problem may be that the input is gzipped. See:
https://github.com/richardmleggett/nextclip/pull/13
Someone has provided a change to enable gzipped files, but I haven't yet merged it into the core codebase. In the meantime, you could use Nathan's suggestion for process substitution, or just unzip first.
Thanks,
Richard
