### ISSUE TITLE
NextClip isn't not seeing one of the read files

### ISSUE THREAD

**Issue by tarunaaggarwal** [richardmleggett/nextclip#16]
Hi,

I'm running the following commands and getting the error below it. I have double-checked the files and my R1 and R2 are present in the directory, but for some reason NextClip is not reading the R2 file. Any suggestions?

/fungi/taruna/bin/nextclip/scripts/nextclip_lmp_analysis.pl \
-config /fungi/taruna/geosmithia/trim/gm5/nextclip2/gm5_mp_index.txt \
-bwathreads 8

 'Error: read 1 file does not exist' 

Thanks,
Taruna

**Comment by richardmleggett** [comment]
Hi Taruna,

In your config file, you should have a line of the format read_one:filename and it's having trouble finding 'filename'. One thing to look for is whitespace at the end of the line - this can confuse it. Failing that, copy the text after the colon and paste it after a 'ls' command, just to double-check there's no typos. If you're absolutely certain there are no typos or whitespace, send me the config file and I'll check it looks correct.

Thanks,
Richard



/fungi/taruna/geosmithia/trim/gm5/nextclip2/gm5_mp_index.txt

On 25 Feb 2015, at 19:26, Taruna <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I'm running the following commands and getting the error below it. I have double-checked the files and my R1 and R2 are present in the directory, but for some reason NextClip is not reading the R2 file. Any suggestions?

/fungi/taruna/bin/nextclip/scripts/nextclip_lmp_analysis.pl \
-config /fungi/taruna/geosmithia/trim/gm5/nextclip2/gm5_mp_index.txt \
-bwathreads 8

'Error: read 1 file does not exist'

Thanks,
Taruna

**Comment by tarunaaggarwal** [comment]
Hi Richard,

Thank you for that feedback. It worked! But now I'm having problems running the 'nextclip_lmp_analysis.pl' script. Once I run it, I keep getting the error message that 'nextclip_lmp_analysis.pl' is not a directory or file. Do you have thoughts regarding why the computer is not finding that script? I already tried typing the full PATH after the 'ls' command to check if the script works or exists, but I get the same error message. Thanks!

Taruna

**Comment by richardmleggett** [comment]
Hi Taruna,

Sounds like it's not finding the script. The scripts need to be put somewhere specified by your PATH environment variable, or added to the PATH variable. To find out where you PATH variable points to, type:
echo $PATH

To add the scripts directory to your path, you do
export PATH=/path/to/scripts/directory:$PATH

(Where /path/to/scripts/directory points to the nextclip scripts directory). Note, this only lasts for the current terminal session, unless you add it to something like .bashrc. If you're unsure about any of this, someone at your institute who knows about Linux should be able to help you...

Thanks,
Richard




On 26 Feb 2015, at 11:21, Taruna <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Richard,

Thank you for that feedback. It worked! But now I'm having problems running the 'nextclip_lmp_analysis.pl' script. Once I run it, I keep getting the error message that 'nextclip_lmp_analysis.pl' is not a directory or file. Do you have thoughts regarding why the computer is not finding that script? I already tried typing the full PATH after the 'ls' command to check if the script works or exists, but I get the same error message. Thanks!

Taruna

**Comment by tarunaaggarwal** [comment]
Great! I will do that. Thanks so much!
